"""Increase email field length

Revision ID: 1342d468cf20
Revises: e62ee895e41a
Create Date: 2024-09-07 19:00:33.255785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1342d468cf20'
down_revision = 'e62ee895e41a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
