"""Изменения в типе данных столбца photo

Revision ID: 90045c3e3401
Revises: 
Create Date: 2024-04-03 21:03:02.915223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90045c3e3401'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estate', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estate', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
