"""Увеличение длины столбца пароля

Revision ID: e62ee895e41a
Revises: 2ad9901bf3da
Create Date: 2024-07-27 20:57:18.131847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e62ee895e41a'
down_revision = '2ad9901bf3da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_log')
    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    op.create_table('change_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('change_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('old_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='change_log_pkey')
    )
    # ### end Alembic commands ###
